[package]
name = "monarch"
version = "0.1.0"
edition = "2021"

[lib]
name = "monarch"
crate-type = ["cdylib", "rlib"]

[dependencies]
detour3 = "*"
paste = "1.0.11"
tracing = "0.1.37"
winapi = "0.3.9"

